### ISSUE TITLE
Ошибка при селекторах состоящих только из псевдоселекторов

### ISSUE THREAD

**Issue by veged** [afelix/setochka#4]
Очень возможно что это баг cssp, но вот такие стили не обрабатываются:

``` css
:link:hover, :visited:hover { color: #f00 !important }
```
